//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSphere.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataSphere.Resources.Locales.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close_title.
        /// </summary>
        internal static string close_title {
            get {
                return ResourceManager.GetString("close_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection_title.
        /// </summary>
        internal static string connection_title {
            get {
                return ResourceManager.GetString("connection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_add_title.
        /// </summary>
        internal static string ctx_add_title {
            get {
                return ResourceManager.GetString("ctx_add_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_delete_title.
        /// </summary>
        internal static string ctx_delete_title {
            get {
                return ResourceManager.GetString("ctx_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_edit_title.
        /// </summary>
        internal static string ctx_edit_title {
            get {
                return ResourceManager.GetString("ctx_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_folder_title.
        /// </summary>
        internal static string ctx_folder_title {
            get {
                return ResourceManager.GetString("ctx_folder_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_mysql_title.
        /// </summary>
        internal static string ctx_mysql_title {
            get {
                return ResourceManager.GetString("ctx_mysql_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ctx_rename_title.
        /// </summary>
        internal static string ctx_rename_title {
            get {
                return ResourceManager.GetString("ctx_rename_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_host_title.
        /// </summary>
        internal static string dalog_conn_host_title {
            get {
                return ResourceManager.GetString("dalog_conn_host_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_name_title.
        /// </summary>
        internal static string dalog_conn_name_title {
            get {
                return ResourceManager.GetString("dalog_conn_name_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_password_title.
        /// </summary>
        internal static string dalog_conn_password_title {
            get {
                return ResourceManager.GetString("dalog_conn_password_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_port_title.
        /// </summary>
        internal static string dalog_conn_port_title {
            get {
                return ResourceManager.GetString("dalog_conn_port_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_save_pw_title.
        /// </summary>
        internal static string dalog_conn_save_pw_title {
            get {
                return ResourceManager.GetString("dalog_conn_save_pw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_type_title.
        /// </summary>
        internal static string dalog_conn_type_title {
            get {
                return ResourceManager.GetString("dalog_conn_type_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dalog_conn_usname_title.
        /// </summary>
        internal static string dalog_conn_usname_title {
            get {
                return ResourceManager.GetString("dalog_conn_usname_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dialog_connectset_title.
        /// </summary>
        internal static string dialog_connectset_title {
            get {
                return ResourceManager.GetString("dialog_connectset_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgbox_cancel_title.
        /// </summary>
        internal static string msgbox_cancel_title {
            get {
                return ResourceManager.GetString("msgbox_cancel_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgbox_delete_ques_summary.
        /// </summary>
        internal static string msgbox_delete_ques_summary {
            get {
                return ResourceManager.GetString("msgbox_delete_ques_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgbox_delete_ques_title.
        /// </summary>
        internal static string msgbox_delete_ques_title {
            get {
                return ResourceManager.GetString("msgbox_delete_ques_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgbox_ok_title.
        /// </summary>
        internal static string msgbox_ok_title {
            get {
                return ResourceManager.GetString("msgbox_ok_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_db_summary.
        /// </summary>
        internal static string page_db_summary {
            get {
                return ResourceManager.GetString("page_db_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_db_title.
        /// </summary>
        internal static string page_db_title {
            get {
                return ResourceManager.GetString("page_db_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_home_summary.
        /// </summary>
        internal static string page_home_summary {
            get {
                return ResourceManager.GetString("page_home_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_home_title.
        /// </summary>
        internal static string page_home_title {
            get {
                return ResourceManager.GetString("page_home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_about_title.
        /// </summary>
        internal static string page_settings_about_title {
            get {
                return ResourceManager.GetString("page_settings_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_app_theme_summary.
        /// </summary>
        internal static string page_settings_app_theme_summary {
            get {
                return ResourceManager.GetString("page_settings_app_theme_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_app_theme_title.
        /// </summary>
        internal static string page_settings_app_theme_title {
            get {
                return ResourceManager.GetString("page_settings_app_theme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_auto_hide_nav_summary.
        /// </summary>
        internal static string page_settings_auto_hide_nav_summary {
            get {
                return ResourceManager.GetString("page_settings_auto_hide_nav_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_auto_hide_nav_title.
        /// </summary>
        internal static string page_settings_auto_hide_nav_title {
            get {
                return ResourceManager.GetString("page_settings_auto_hide_nav_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_contact_us_title.
        /// </summary>
        internal static string page_settings_contact_us_title {
            get {
                return ResourceManager.GetString("page_settings_contact_us_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_corner_radius_summary.
        /// </summary>
        internal static string page_settings_corner_radius_summary {
            get {
                return ResourceManager.GetString("page_settings_corner_radius_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_corner_radius_title.
        /// </summary>
        internal static string page_settings_corner_radius_title {
            get {
                return ResourceManager.GetString("page_settings_corner_radius_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_display_material_summary.
        /// </summary>
        internal static string page_settings_display_material_summary {
            get {
                return ResourceManager.GetString("page_settings_display_material_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_display_material_title.
        /// </summary>
        internal static string page_settings_display_material_title {
            get {
                return ResourceManager.GetString("page_settings_display_material_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_display_summary.
        /// </summary>
        internal static string page_settings_languageset_display_summary {
            get {
                return ResourceManager.GetString("page_settings_languageset_display_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_display_title.
        /// </summary>
        internal static string page_settings_languageset_display_title {
            get {
                return ResourceManager.GetString("page_settings_languageset_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_languageset_title.
        /// </summary>
        internal static string page_settings_languageset_title {
            get {
                return ResourceManager.GetString("page_settings_languageset_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_personalization_title.
        /// </summary>
        internal static string page_settings_personalization_title {
            get {
                return ResourceManager.GetString("page_settings_personalization_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_summary.
        /// </summary>
        internal static string page_settings_summary {
            get {
                return ResourceManager.GetString("page_settings_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page_settings_title.
        /// </summary>
        internal static string page_settings_title {
            get {
                return ResourceManager.GetString("page_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save_title.
        /// </summary>
        internal static string save_title {
            get {
                return ResourceManager.GetString("save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_need_restart_app_summary.
        /// </summary>
        internal static string sys_need_restart_app_summary {
            get {
                return ResourceManager.GetString("sys_need_restart_app_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ucrt_empty_summary.
        /// </summary>
        internal static string ucrt_empty_summary {
            get {
                return ResourceManager.GetString("ucrt_empty_summary", resourceCulture);
            }
        }
    }
}
